config/routes.rb
Rails.application.routes.draw do
  # get "static_pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"


  resources :confirmations, only: [:create, :edit, :new]
  # resources :users do
  #   resources :friendships
  # end
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  get "user/:id", to: "users#get_by_id"

  get "friends", to: "users#get"
  post "friends", to: "friendships#post"
  delete "unfriend", to: "friendships#destroy"
  get "my_friends", to: "friendships#get"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  has_secure_password
  MAILER_FROM_EMAIL = "no-reply@trial-jpzkmgqmxd1l059v.mlsender.net"

  attr_accessor :current_password
  before_save :downcase_unconfirmed_email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  validates :unconfirmed_email, format: { with: URI::MailTo::EMAIL_REGEXP, allow_blank: true }

  # validates :profile_name, presence: true, length: {minimum:3}
  # validates :description, presence: true, length: {minimum:1}
  # has_many :primary_friends, class_name: "User", foreign_key: "user_one"
  # has_many :secondary_friends, class_name: "User", foreign_key: "user_two"
  has_many :friendships
  has_many :users, through: :friendships
  has_many :active_sessions, dependent: :destroy
  

  def downcase_email
    self.email = email.downcase
  end

  def confirm!
    if unconfirmed_or_reconfirming?
      ActiveRecord::Base.transaction do
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    end
      true
    else
      false
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end
  
  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def unconfirmed?
    !confirmed?
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  private
  
  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:edit, :destroy, :update]
  before_action :redirect_if_authenticated, only: [:create, :new]

  def create
    @user = User.new(create_user_params)
    @user.unconfirmed_email = @user.email
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  def get
    @friends = User.where.not(id: [ current_user.id ]).order("RANDOM()").limit(3)
  end

  def get_by_id
    @user = User.where(id: params[:id]).first
  end
  # def add_friend
  #   @user = current_user
  #   Friendship.create(user_id: @user.id, friend_id: params[:id])
  # end
  private
  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email, :profile_name, :description)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1>new user</h1>

<%= form_with model: user do |form| %>

    <div>
        <%= form.label :username %><br>
        <%= form.text_field :username %>
        <%= user.errors.full_messages_for(:username).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :password %><br>
        <%= form.text_field :password %>
        <%= user.errors.full_messages_for(:password).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :profile_name %><br>
        <%= form.text_field :profile_name %>
        <%= user.errors.full_messages_for(:profile_name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
        <%= user.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.label :display_name %>
    <%= form.text_field :profile_name, required: false %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description, required: false %>
  </div>
  <hr/>
  <div>
    <%= form.label :email, "Current Email" %>
    <%= form.email_field :email, disabled: true %>
  </div>
  <div>
    <%= form.label :unconfirmed_email, "New Email" %>
    <%= form.text_field :unconfirmed_email %>
  </div>
  <div>
    <%= form.label :password, "Password (leave blank if you don't want to change it)" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <hr/>
  <div>
    <%= form.label :current_password, "Current password (we need your current password to confirm your changes)" %>
    <%= form.password_field :current_password, required: true %>
  </div>
  <%= form.submit "Update Account" %>
  <% end %>
  
  <h2>Current Logins</h2>
  <% if @active_sessions.any? %>
  <%= button_to "log out of all other sessions", destroy_all_active_sessions_path, method: :delete %>
  <table>
    <thead>
      <tr>
        <th>User Agent</th>
        <th>IP Address</th>
        <th>Signed In At</th>
        <th>Sign Out</th>
      </tr>
    </thead>
    <tbody>
      <%= render @active_sessions %>
    </tbody>
  </table>
<% end %>

app/views/users/get.html.erb
<div>
  Check out these cool users!
</div>
<div id="friends container">
  <% @friends.each do |friend| %>
  <div id="individualFriend">
    <div>
      <%= friend.profile_name %>
    </div>
    <div>
      <%= friend.description %>
    </div>
    <div>
      <%= link_to "User Info", "/user/#{friend.id}" %>
    </div>
  </div>
  <% end %>
  <div>
    <%= button_to "Get new batch", request.original_url, method: :get %>
  </div>
</div>

app/views/users/get_by_id.html.erb
<div>
  <%if current_user %>
    <h1><%= @user.profile_name %></h1>
    <p><%= @user.email %></p>
    <h2><%= @user.description %></h2>
    <div>
      <%= button_to "add friend", friends_path(id: @user.id), method: :post %>
    </div>
    <div>
      <%= button_to "execute friend", unfriend_path(id: @user.id), method: :delete %>
    </div>
  <% else %>
    <div>Please log in to view</div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
<p>
    <%= link_to user.username, user %>
</p>

<% end %>

<%= link_to "new user", new_user_path %>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path do |form|  %>
    <%= render partial: "shared/form_errors", locals: { object: form.object} %>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email, required: true %>
    </div>

    <div>
        <%= form.label :password %>
        <%= form.password_field :password, required: true %>
    </div>

    <div>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, required: true %>
    </div>

    <%
=begin%>
 <div>
        <%= form.label :profile_name %>
        <%= form.text_field :profile_name, required: true %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_field :description, required: true %>
    </div> 
<%
=end%>

    <%= form.submit "sign up" %>
<% end %>

app/views/users/show.html.erb
<h1>
    <%= @user.profile_name %>
</h1>
<h2>
    <%= @user.description %>
</h2>

<%=link_to "Edit", edit_user_path(@user) %>
<%=link_to "Destroy", user_path(@user), data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?' 
} %>