config/routes.rb
Rails.application.routes.draw do
  # get "static_pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"


  resources :confirmations, only: [:create, :edit, :new]
  # resources :users do
  #   resources :friendships
  # end
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  get "user/:id", to: "users#get_by_id"

  get "friends", to: "users#get"
  post "friends", to: "friendships#post"
  delete "unfriend", to: "friendships#destroy"
  get "my_friends", to: "friendships#get"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby Friends" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- <link rel="manifest" href="/manifest.json"> -->
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% flash.each do |message_type, message| %>
        <div class="<%= message_type %>"><%= message %></div>
      <% end %>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "My Friends", my_friends_path, method: :get %></li>
          <li><%= link_to "Find Friends", friends_path, method: :get %></li>
          <li><%= link_to "My Account", account_path %></li>
           <li><%= button_to "Logout", logout_path, method: :delete %></li>
        <% else %>
           <li><%= link_to "Login", login_path %></li>
           <li><%= link_to "Sign Up", sign_up_path %></li>
           <li><%= link_to "Forgot my password", new_password_path %></li>
           <li><%= link_to "Didn't receive confirmation instructions", new_confirmation_path %></li>
        <% end %>
      </ul>
      <hr/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>